### ISSUE TITLE
The pretrained model is missing.

### ISSUE THREAD

**Issue by odddeer** [ahirsharan/SegNet#2]
![image](https://user-images.githubusercontent.com/63915031/163570234-10fb8cb2-e4ca-4d81-be03-ab0559514b31.png)
Thanks for your sharing.
Could you offer the pretrained model to the github?

**Comment by ahirsharan** [comment]
Hey!
I did try to train the model with the existing implementation, but I could not get results anywhere near the original paper. Hence, I was not sure if the implementation was correct, and I thought I would maybe work on this later. Now, I see your comment nearly a year later and realized, I never got the time to continue this project. Sorry, I do not have the pretrained model for this available.
